name: Convert TS to MP4


on:
  push:
    paths:
      - "**/*.ts"
      - "**/*.TS"
      - "**/*.pdf"
      - "**/*.PDF"
      - "**/*.rtf"
      - "**/*.RTF"

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Commit and push files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add **/*.ts **/*.TS **/*.pdf **/*.PDF **/*.rtf **/*.RTF
          git commit -m "Auto commit TS / PDF / RTF" || echo "No changes to commit"

      - name: Push changes
        run: git push
